### ISSUE TITLE
Support columns

### ISSUE THREAD

**Issue by nofxx** [mchelem/terminator-editor-plugin#6]
A very common syntax is FILE:LINE:COL  or sometimes FILE#LINE:COL.

```
/home/nofxx/nice/file.rb:30:10  # Something very wrong here
```

Emacs for instance, as many other editors, also support column in the args, 
clicking on that link would result in the cursor on the line and column.

**Comment by fotanus** [comment]
This is also true for vim. 
@mchelem any downsides on support this?

**Comment by nofxx** [comment]
Here's how I did it: 

https://github.com/nofxx/xxpub/blob/master/home/.config/terminator/plugins/files.py#L17

**Comment by fotanus** [comment]
@nofxx thanks, if @mchelem wants this feature I can send the PR.

**Comment by nofxx** [comment]
@fotanus please do. I don't code python. 
That's was the first time I've played with it.

**Comment by mchelem** [comment]
@fotanus No downsides, but I'd like to allow more flexibility in column positioning (instead of assuming column always comes after line).

Specific to vim: I had an issue moving to a given column when using remote-silent. See http://stackoverflow.com/questions/19750910/vim-go-to-line-column-with-remote-silent
I wasn't able to make any proposed solutions work back then.

The [cursor solution](http://stackoverflow.com/a/23702299) seems to be working now, so I'll give it another try.

**Comment by hugomaiavieira** [comment]
I use this with success on vscode. I just had to adjust the regex to the column part be optional, to be able to use on paths with or without column:

``` python
match = "([^ \t\n\r\f\v:]+?):([0-9]+):?([0-9]+)?"
```

Now it works with *./file:45* and *./file:45:20*, for example.

It is worth to add this information at readme?

**Comment by mchelem** [comment]
@hugomaiavieira Good to know it is working for you. Do you want to include this with your PR?

**Comment by hugomaiavieira** [comment]
@mchelem done
